[package]
name = "spiffe"
version = "0.1.0"
authors = ["Sabree Blackmon <sabree@heavypackets.sh>"]

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
error-chain = "0.12.0"
hyper = "0.10.0"
grpc = "~0.5"
protobuf = "~2"
tls-api = "~0.1"

[dev-dependencies]
assert_matches = "1.3"