[package]
name = "spiffe"
version = "0.1.0"
authors = ["Sabree Blackmon <sabree@heavypackets.sh>"]

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
error-chain = "0.12.0"
hyper = "0.10.0"
protobuf = "~2"
grpcio = "^0.3"
futures = "^0.1.15"

[dev-dependencies]
assert_matches = "1.3"